### ISSUE TITLE
[BUG] 🐛  `ManageSecrets` target fails to run

### ISSUE THREAD

**Issue by candoumbe** [candoumbe/Pipelines#94]
## Usage Information ##

Package version : 0.6.0

## Relevant Code / Invocations
```pwsh
./build manage-secrets
```
     
## Expected Behavior
The target should run with no error and I should be able to manage secrets

## Stacktrace / Exception
```
PowerShell Core version 7.3.6
Microsoft (R) .NET SDK version 7.0.400

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 7.0.2 (Windows,.NETCoreApp,Version=v7.0)

12:39:24 [INF] > "C:\Program Files\dotnet\dotnet.exe" C:\Users\ndoum\.nuget\packages\gitversion.tool\5.11.1\tools\net5.0\any\gitversion.dll /nocache /nofetch

╬══════════════════
║ ManageSecrets
╬═════════

Profile name
¬  development
12:39:35 [INF] > "C:\Program Files\dotnet\dotnet.exe" tool run nuke :secrets" development"
12:39:35 [DBG] Command 'secrets development' is not supported, available commands are:
12:39:35 [DBG]   - AddPackage
12:39:35 [DBG]   - CakeClean
12:39:35 [DBG]   - CakeConvert
12:39:35 [DBG]   - Complete
12:39:35 [DBG]   - GetConfiguration
12:39:35 [DBG]   - Secrets
12:39:35 [DBG]   - Setup
12:39:35 [DBG]   - Trigger
12:39:35 [DBG]   - Update
12:39:35 [ERR] Target ManageSecrets has thrown an exception
Nuke.Common.Tooling.ProcessException: Process 'dotnet.exe' exited with code 1.
   > "C:\Program Files\dotnet\dotnet.exe" tool run nuke :secrets" development"
   @ C:\Users\ndoum\Projects\Perso\Candoumbe.Types
Standard output:
   Command 'secrets development' is not supported, available commands are:
     - AddPackage
     - CakeClean
     - CakeConvert
     - Complete
     - GetConfiguration
     - Secrets
     - Setup
     - Trigger
     - Update

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Tooling/ProcessExtensions.cs:line 39
   at Nuke.Common.Tooling.ProcessTasks.DefaultExitHandler(ToolSettings toolSettings, IProcess process) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 246
   at Nuke.Common.Tools.DotNet.DotNetTasks.<>c.<DotNet>b__11_0(IProcess p) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 44
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNet(ArgumentStringHandler arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 logger, Action`1 exitHandler) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 44
   at Candoumbe.Pipelines.Components.IHaveSecret.<>c.<get_ManageSecrets>b__1_2() in /_/src/Candoumbe.Pipelines/Components/IHaveSecret.cs:line 30
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119

╬══════════════════════
║ Errors & Warnings
╬═════════════

[ERR] ManageSecrets: Target ManageSecrets has thrown an exception

═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
ManageSecrets      Failed          0:09   // ProcessException: Process 'dotnet.exe' exited with code 1.
───────────────────────────────────────
Total                              0:09
═══════════════════════════════════════
```

**Comment by candoumbe** [comment]
This error is due to the fact that a CLI cannot call another CLI that needs interaction with the user.
This component will be dropped
